### ISSUE TITLE
add image to repo

### ISSUE THREAD

**Issue by greglinch** [xof88/Homepage-Assign#1]
It currently appears as a broken image when I view it, so uploading the file to GitHub should fix that.
![screen shot 2017-06-07 at 1 57 18 pm](https://user-images.githubusercontent.com/327783/26893414-3dd5b966-4b89-11e7-9906-0ad1c2d36afb.png)

**Comment by xof88** [comment]
<img width="680" alt="world map_color 2" src="https://user-images.githubusercontent.com/28675507/27310598-6cd631c4-5529-11e7-8fb1-5c70a8060c03.png">

**Comment by xof88** [comment]
Did that work?
